"""Deterministic artificial test inputs. NEVER observations of real securities."""

import numpy as np
import pandas as pd

from pqr.data.calendar import at_new_york, sessions
from pqr.data.schemas import Dataset, DatasetMetadata, validate_dataset

FIXTURE_WARNING = (
    "SYNTHETIC VERIFICATION FIXTURE — "
    "no real securities, market observations or investment evidence."
)


def verification_dataset(seed: int = 42) -> Dataset:
    rng = np.random.default_rng(seed)
    dates = sessions("2018-01-02", "2025-12-31")
    future = sessions("2018-01-02", "2026-01-09")
    availability = {day: at_new_york(future[i + 1], 8) for i, day in enumerate(dates)}
    ids = [f"TEST{i:02d}" for i in range(1, 21)] + ["TEST_BENCHMARK"]
    market = rng.normal(0.00015, 0.008, len(dates))
    bar_frames, fact_rows, universe_rows = [], [], []
    retrieved = pd.Timestamp("2026-01-10T12:00:00Z")
    for number, asset in enumerate(ids):
        shocks = (
            market if asset == "TEST_BENCHMARK" else market * 0.7 + rng.normal(0, 0.007, len(dates))
        )
        # No parameter is chosen to produce attractive strategy performance.
        prices = (45 + number * 3) * np.cumprod(1 + shocks)
        frame = pd.DataFrame(
            {
                "asset_id": asset,
                "session": dates,
                "close": prices,
                "volume": rng.integers(800_000, 2_000_000, len(dates)),
                "tr_close": prices,
                "available_at": [availability[d] for d in dates],
                "retrieved_at": retrieved,
                "availability_basis": "fixture",
            }
        )
        bar_frames.append(frame)
        if asset == "TEST_BENCHMARK":
            continue
        universe_rows.append(
            {
                "asset_id": asset,
                "member_from": dates[0],
                "member_to": pd.NaT,
                "available_at": pd.Timestamp("2017-12-01T00:00:00Z"),
                "industry": f"Test industry {number % 4 + 1}",
            }
        )
        for year in range(2017, 2026):
            base = (number + 1) * 1_000_000
            fact_rows.append(
                {
                    "asset_id": asset,
                    "period_end": pd.Timestamp(f"{year}-12-31"),
                    "available_at": pd.Timestamp(f"{year + 1}-03-15T13:00:00Z"),
                    "retrieved_at": retrieved,
                    "availability_basis": "fixture",
                    "accession": f"ARTIFICIAL-{asset}-{year}",
                    "net_income": float(base * rng.uniform(-0.04, 0.18)),
                    "assets_begin": float(base),
                    "assets_end": float(base * 1.05),
                }
            )
    meta = DatasetMetadata(
        kind="synthetic_fixture",
        description=FIXTURE_WARNING,
        license="MIT; artificial test inputs generated by this project",
        source="pqr.data.fixtures.verification_dataset",
        retrieved_at=str(retrieved),
        benchmark_id="TEST_BENCHMARK",
        total_return_convention="synthetic",
    )
    return validate_dataset(
        Dataset(
            pd.concat(bar_frames, ignore_index=True),
            pd.DataFrame(fact_rows),
            pd.DataFrame(universe_rows),
            meta,
        )
    )
